services:
  restaurant-app:
    build: .
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - oracle-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./uploads/posts:/app/uploads/posts
      - ./uploads/avatars:/app/uploads/avatars

  oracle-db:
    image: gvenzl/oracle-xe
    ports:
      - "1523:1521"
    environment:
      ORACLE_PASSWORD: hr
      APP_USER: hr
      APP_USER_PASSWORD: hr
