spring:
  application:
    name: friend-finder

  cache:
    type: redis

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  messages:
    basename: i18n/messages
    encoding: UTF-8

  main:
    banner-mode: off

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.authentication: DEBUG
    org.springframework.security.authorization: DEBUG

jwt:
  secret: U29tZVN1cGVyU2VjdXJlU2VjcmV0S2V5MTIzNDU2tkodlsbhnbnxnbfhbdf

server:
  port: 9090


---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:oracle:thin:@//localhost:1523/pdb
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver

file:
  upload-dir: D:/FriendFinderUploads/posts
  avatar-dir: D:/FriendFinderUploads/avatars
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:oracle:thin:@//oracle-db:1523/XEPDB1
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver

file:
  upload-dir: /app/uploads/posts
  avatar-dir: /app/uploads/avatars
